### PR TITLE
Fix scalar exp encoding

### LINKED ISSUE #650: Exp: scalar encoding is incompatible with the parser rules
ExpScalar.toString doesn't follow the rules of the parser. It effectively calls `value.toString()`. The only special rule is that it encloses it in single quotes if it is a char sequence. We need the encoding to be complimentary to the literals grammar used by the parser:

```java
Long l = 3147483647L; // encode as 3147483647L, not 314748364
BigDecimal d = new BigDecimal("2.1000001B"); // encode as 2.1000001B, not 2.1000001
// same for floats...

String s1 = "a'b"; // encode as "a'b", not 'a'b'
String s1 = "a\"'b"; // encode as 'a"\'b, not 'a"'b'
```

### PR DESCRIPTION
**Pull request by m-dzianishchyts**
Fixes #650.

### CODE REVIEW

File: agrest-engine/src/main/java/io/agrest/exp/parser/ExpScalar.java [hunk 1]
```diff
@@ -31,22 +39,44 @@ protected Object transformExpression(Function<Object, Object> transformer) {
...
     @Override
     public String toString() {
+        if (value == null) {
+            return "null";
+        }
         if (value instanceof CharSequence) {
-            return "'" + value + "'";
-        } else {
-            return String.valueOf(value);
+            String quoteChar = scalarImage.substring(0, 1);
```
Comment (stariy95) [inline agrest-engine/src/main/java/io/agrest/exp/parser/ExpScalar.java:64]: Let's try to move this logic to the setter, so here it will simply return `scalarImage`
